version: '3.9'

services:
  db:
    image: mariadb:10
    env_file: docker-compose.env
    volumes:
      - mariadb:/var/lib/mysql:z
    restart: always

  app:
    #image: ghcr.io/rockyhb/dverein
    build: .
    env_file: docker-compose.env
    volumes:
      - staticfiles:/var/www/static:z
    depends_on:
      - db

  web:
    image: nginx:alpine
    volumes:
      - ./docker-setup/nginx-app.conf:/etc/nginx/conf.d/default.conf:ro,z
      - staticfiles:/var/www/static:ro,z
    depends_on:
      - app
    ports:
      - 8000:80
    restart: always

volumes:
  mariadb:
  staticfiles:
