from . import Abrechnungslauf
from . import Adresstyp
from . import Anfangsbestand
from . import Arbeitseinsatz
from . import Beitragsgruppe
from . import Buchung
from . import Buchungdokument
from . import Buchungsart
from . import Buchungsklasse
from . import Eigenschaft
from . import Eigenschaften
from . import Eigenschaftgruppe
from . import Einstellung
from . import Felddefinition
from . import Formular
from . import Formularfeld
from . import Jahresabschluss
from . import Konto
from . import Kursteilnehmer
from . import Lastschrift
from . import Lehrgang
from . import Lehrgangart
from . import Lesefeld
from . import Mail
from . import Mailanhang
from . import Mailempfaenger
from . import Mailvorlage
from . import Mitglied
from . import Mitglieddokument
from . import Mitgliedfoto
from . import Mitgliednextbgruppe
from . import Mitgliedskonto
from . import Projekt
from . import Qifimporthead
from . import Qifimportpos
from . import Spendenbescheinigung
from . import Suchprofil
from . import Version
from . import Wiedervorlage
from . import Zusatzabbuchung
from . import Zusatzbetragabrechnungslauf
from . import Zusatzfelder
