from django.db import models
from django.db.models.deletion import CASCADE, SET_NULL
from django.db.models.expressions import F
from django.db.models.fields import BinaryField, BooleanField, CharField, DateField, DateTimeField, FloatField, IntegerField, TextField
from django.db.models.fields.related import ForeignKey
from django.db.models.lookups import In

class Einstellung(models.Model):
    name = CharField(null=True, max_length=70)
    strasse = CharField(null=True, max_length=50)
    plz = CharField(null=True, max_length=5)
    ort = CharField(null=True, max_length=50)
    finanzamt = CharField(null=True, max_length=30)
    bescheiddatum = DateField(null=True)
    vorlaeufig = BooleanField(default=False)
    vorlaeufigab = DateField(null=True)
    beguenstigterzweck = CharField(null=True, max_length=100)
    mitgliedsbeitraege = BooleanField(default=False)
    bic = CharField(null=True, max_length=11)
    iban = CharField(null=True, max_length=34)
    glaeubigerid = CharField(null=True, max_length=35)
    blz = CharField(null=True, max_length=8)
    konto = CharField(null=True, max_length=12)
    geburtsdatumpflicht = BooleanField(default=False)
    eintrittsdatumpflicht = BooleanField(default=False)
    sterbedatum = BooleanField(default=False)
    kommunikationsdaten = BooleanField(default=False)
    zusatzabbuchung = BooleanField(default=False)
    vermerke = BooleanField(default=False)
    wiedervorlage = BooleanField(default=False)
    kursteilnehmer = BooleanField(default=False)
    lehrgaenge = BooleanField(default=False)
    juristischepersonen = BooleanField(default=False)
    mitgliedfoto = BooleanField(default=False)
    uselessfelder = CharField(null=True, max_length=5)
    auslandsadressen = BooleanField(default=False)
    arbeitseinsatz = BooleanField(default=False)
    dokumentenspeicherung = BooleanField(default=False)
    individuellebeitraege = BooleanField(default=False)
    rechnungtextabbuchung = CharField(null=True, max_length=100)
    rechnungtextueberweisung = CharField(null=True, max_length=100)
    rechnungtextbar = CharField(null=True, max_length=100)
    externemitgliedsnummer = BooleanField(default=False)
    beitragsmodel = IntegerField(null=True)
    dateinamenmuster = CharField(null=True, max_length=50)
    dateinamenmusterspende = CharField(null=True, max_length=50)
    vorlagencsvverzeichnis = CharField(null=True, max_length=200)
    spendenbescheinigungminbetrag = FloatField(null=True)
    spendenbescheinigungverzeichnis = CharField(null=True, max_length=200)
    spendenbescheinigungprintbuchungsart = BooleanField(default=False)
    veranlagungvon = DateField(null=True)
    veranlagungbis = DateField(null=True)
    beginngeschaeftsjahr = CharField(null=True, max_length=6)
    smtp_server = CharField(null=True, max_length=50)
    smtp_port = CharField(null=True, max_length=5)
    smtp_auth_user = CharField(null=True, max_length=50)
    smtp_from_address = CharField(null=True, max_length=50)
    smtp_from_anzeigename = CharField(null=True, max_length=50)
    smtp_ssl = BooleanField(default=False)
    zahlungsweg = IntegerField(null=True)
    zahlungsrhytmus = IntegerField(null=True)
    defaultland = CharField(null=True, max_length=2)
    altersgruppen = CharField(null=True, max_length=200)
    jubilaeen = CharField(null=True, max_length=50)
    jubilarstartalter = CharField(null=True, max_length=10)
    altersjubilaeen = CharField(null=True, max_length=50)
    arbeitsmodel = IntegerField(default=1)
    altermodel = IntegerField(default=1)
    zusatzbetragausgetretene = BooleanField(default=False)
    mandatid_source = IntegerField(default=1)
    mail_always_bcc = CharField(null=True, max_length=140)
    mail_always_cc = CharField(null=True, max_length=140)
    copy_to_imap_folder = BooleanField(default=False)
    imap_ssl = BooleanField(default=False)
    imap_starttls = BooleanField(default=False)
    imap_auth_user = CharField(null=True, max_length=140)
    imap_host = CharField(null=True, max_length=140)
    imap_port = CharField(null=True, max_length=140)
    imap_sent_folder = CharField(null=True, max_length=140)
    autobuchungsuebernahme = BooleanField(default=True)
    mailsignatur = CharField(default='', max_length=1000)
    unterdrueckungohnebuchung = BooleanField(default=False)
    sepadatumoffset = IntegerField(default=0)
        