from django.db import models
from django.db.models.deletion import CASCADE, SET_NULL
from django.db.models.expressions import F
from django.db.models.fields import BinaryField, BooleanField, CharField, DateField, DateTimeField, FloatField, IntegerField, TextField
from django.db.models.fields.related import ForeignKey
from django.db.models.lookups import In

class Mitglied(models.Model):
    externemitgliedsnummer = CharField(null=True, max_length=50, unique=True)
    adresstyp = ForeignKey('Adresstyp', null=True, on_delete=SET_NULL)
    personenart = CharField(null=True, max_length=1)
    anrede = CharField(null=True, max_length=40)
    titel = CharField(null=True, max_length=40)
    name = CharField(max_length=40)
    vorname = CharField(null=True, max_length=40)
    adressierungszusatz = CharField(null=True, max_length=40)
    strasse = CharField(max_length=40)
    plz = CharField(max_length=10)
    ort = CharField(max_length=40)
    staat = CharField(null=True, max_length=50)
    zahlungsweg = IntegerField(null=True)
    zahlungsrhytmus = IntegerField(null=True)
    mandatdatum = DateField(null=True)
    mandatversion = IntegerField(null=True)
    mandatsequence = CharField(null=True, max_length=4)
    bic = CharField(null=True, max_length=11)
    iban = CharField(null=True, max_length=34)
    blz = CharField(null=True, max_length=8)
    konto = CharField(null=True, max_length=16)
    ktoipersonenart = CharField(null=True, max_length=1)
    ktoianrede = CharField(null=True, max_length=40)
    ktoititel = CharField(null=True, max_length=40)
    ktoiname = CharField(null=True, max_length=40)
    ktoivorname = CharField(null=True, max_length=40)
    ktoistrasse = CharField(null=True, max_length=40)
    ktoiadressierungszusatz = CharField(null=True, max_length=40)
    ktoiplz = CharField(null=True, max_length=10)
    ktoiort = CharField(null=True, max_length=40)
    ktoistaat = CharField(null=True, max_length=50)
    ktoiemail = CharField(null=True, max_length=50)
    ktoigeschlecht = CharField(null=True, max_length=1)
    geburtsdatum = DateField(null=True)
    geschlecht = CharField(null=True, max_length=1)
    telefonprivat = CharField(null=True, max_length=20)
    telefondienstlich = CharField(null=True, max_length=20)
    handy = CharField(null=True, max_length=20)
    email = CharField(null=True, max_length=50)
    eintritt = DateField(null=True)
    beitragsgruppe = ForeignKey('Beitragsgruppe', null=True, on_delete=SET_NULL)
    individuellerbeitrag = FloatField(null=True)
    zahlerid = ForeignKey('self', null=True, on_delete=SET_NULL)
    austritt = DateField(null=True)
    kuendigung = DateField(null=True)
    sterbetag = DateField(null=True)
    vermerk1 = CharField(null=True, max_length=2000)
    vermerk2 = CharField(null=True, max_length=2000)
    eingabedatum = DateField(null=True)
    letzteaenderung = DateField(null=True)
    zahlungstermin = IntegerField(null=True)
    