from django.contrib import admin

from .models import *

admin.site.register(Abrechnungslauf)
admin.site.register(Adresstyp)
admin.site.register(Anfangsbestand)
admin.site.register(Arbeitseinsatz)
admin.site.register(Beitragsgruppe)
admin.site.register(Buchungdokument)
admin.site.register(Buchung)
admin.site.register(Buchungsart)
admin.site.register(Buchungsklasse)
admin.site.register(Eigenschaften)
admin.site.register(Eigenschaftgruppe)
admin.site.register(Eigenschaft)
admin.site.register(Einstellung)
admin.site.register(Felddefinition)
admin.site.register(Formularfeld)
admin.site.register(Formular)
admin.site.register(Jahresabschluss)
admin.site.register(Konto)
admin.site.register(Kursteilnehmer)
admin.site.register(Lastschrift)
admin.site.register(Lehrgangart)
admin.site.register(Lehrgang)
admin.site.register(Lesefeld)
admin.site.register(Mailanhang)
admin.site.register(Mailempfaenger)
admin.site.register(Mail)
admin.site.register(Mailvorlage)
admin.site.register(Mitglieddokument)
admin.site.register(Mitgliedfoto)
admin.site.register(Mitgliednextbgruppe)
admin.site.register(Mitglied)
admin.site.register(Mitgliedskonto)
admin.site.register(Projekt)
admin.site.register(Qifimporthead)
admin.site.register(Qifimportpos)
admin.site.register(Spendenbescheinigung)
admin.site.register(Suchprofil)
admin.site.register(Version)
admin.site.register(Wiedervorlage)
admin.site.register(Zusatzabbuchung)
admin.site.register(Zusatzbetragabrechnungslauf)
admin.site.register(Zusatzfelder)
